# Generated by Django 2.2.9 on 2020-06-17 01:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('session_name', models.CharField(blank=True, max_length=16, null=True)),
                ('session_scope', models.CharField(blank=True, max_length=256, null=True)),
                ('session_from', models.DateTimeField(blank=True, null=True)),
                ('session_to', models.DateTimeField(blank=True, null=True)),
                ('session_room', models.CharField(blank=True, max_length=16, null=True)),
                ('session_max_attendees', models.IntegerField(null=True)),
                ('session_current_attendees', models.IntegerField(null=True)),
                ('session_presentators', wagtail.core.fields.StreamField([('se_presentator', wagtail.core.blocks.StructBlock([('presentator_name', wagtail.core.blocks.CharBlock(blank=False, help_text='Name of the presentator', null=True)), ('presentator_email', wagtail.core.blocks.EmailBlock(blank=True, help_text='Important! Format ci@s.co', null=True)), ('presentator_link', wagtail.core.blocks.URLBlock(blank=True, help_text='Important! Format https://www.domain.tld/xyz', null=True))], blank=False, icon='fa-id-badge', null=True))], null=True)),
                ('session_attendees', wagtail.core.fields.StreamField([('se_attendee', wagtail.core.blocks.StructBlock([('attendee_name', wagtail.core.blocks.CharBlock(blank=False, help_text='Name of the attendee', null=True)), ('attendee_email', wagtail.core.blocks.EmailBlock(blank=True, help_text='Important! Format ci@s.co', null=True)), ('attendee_attendance', wagtail.core.blocks.BooleanBlock(default=False, help_text='Whether the attendee was attending or not', required=True)), ('attendee_cache', wagtail.core.blocks.TextBlock(blank=True, help_text='Other information', null=True))], blank=False, icon='fa-credit-card', null=True))], blank=True, null=True)),
                ('session_cache', models.TextField(blank=True, null=True)),
                ('session_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
    ]
